// Generated by scrapeLeetcodeTestcases.ts for problem: two-sum
// From: https://leetcode.com/problems/two-sum/
// Timestamp: 2025-09-22T08:46:23.514Z
//
// IMPORTANT NOTE:
// LeetCode employs bot detection (like Cloudflare) which may block automated scripts
// like this one, resulting in a 403 Forbidden error or incomplete data.
// For reliable scraping, a more advanced setup using a headless browser (e.g., Puppeteer)
// that can execute JavaScript and mimic real user interaction might be necessary.
// This script provides a best-effort attempt with basic HTTP requests.

import { TestCase } from "@algolens/core/src/types";
// Note: You might need to adjust the import path for TestCase based on your project structure.
// For problem-specific types, you would import them from './types';
// e.g., import { two-sumInput, two-sumOutput } from "./types";

export const testcases: TestCase<any, any>[] = [
  {
    name: "Scraped Example 1",
    input: {
      nums: [2, 7, 11, 15],
      target: 9,
    },
    expected: [0, 1],
    description: "Because nums[0] + nums[1] == 9, we return [0, 1].",
  },
  {
    name: "Scraped Example 2",
    input: {
      nums: [3, 2, 4],
      target: 6,
    },
    expected: [1, 2],
    description: "Because nums[1] + nums[2] == 6, we return [1, 2].",
  },
  {
    name: "Scraped Example 3",
    input: {
      nums: [3, 3],
      target: 6,
    },
    expected: [0, 1],
    description: "Because nums[0] + nums[1] == 6, we return [0, 1].",
  },
  {
    name: "Additional Test Case 4",
    input: {
      nums: [1, 5, 3, 7],
      target: 8,
    },
    expected: [1, 2],
    description: "Because nums[1] + nums[2] == 8, we return [1, 2].",
  },
];

// Reminder: Review scraped test cases for accuracy and completeness.
// Complex data structures might require manual adjustments to the parsed input/expected values.
